-- SAML federation metadata. Primary identifiers are ULIDs generated by the application.

CREATE TABLE saml_providers (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    idp_entity_id TEXT NOT NULL,
    idp_sso_url TEXT NOT NULL,
    idp_certificate_pem TEXT,
    sp_entity_id TEXT NOT NULL,
    acs_url TEXT NOT NULL,
    name_id_format TEXT,
    schema_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE saml_requests (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES saml_providers(id) ON DELETE CASCADE,
    relay_state TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_saml_providers_tenant_id ON saml_providers(tenant_id);
CREATE INDEX idx_saml_requests_tenant_id ON saml_requests(tenant_id);
CREATE INDEX idx_saml_requests_provider_id ON saml_requests(provider_id);
