[package]
name = "sso-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "sso-gateway"
path = "src/main.rs"

[dependencies]
sunbeam-g2v = { workspace = true }
connectrpc = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
reqwest = { workspace = true }
axum = { workspace = true }
sso-ory-client = { path = "../sso-ory-client", default-features = false }
sso-openfga-client = { workspace = true, optional = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ulid = { workspace = true }
time = { workspace = true }
gamlastan = "0.6"
chrono = "0.4"
base64 = "0.22"
sha2 = "0.10"
hmac = "0.12"
hkdf = "0.12"
rand = "0.8"
hex = "0.4"
jsonschema = "0.29"
hickory-resolver = "0.26"
jsonwebtoken = { version = "10", features = ["aws_lc_rs"] }
async-trait = "0.1"
urlencoding = "2"
url = "2"
subtle = "2.6"
aes-gcm = "0.10"

[dev-dependencies]
rsa = "0.9"
rcgen = "0.13"
sunbeam-test = { git = "https://github.com/sunbeamdotpt/test.git", rev = "3ef953ca05234206ff62ea860da24a508a0a02c6" }
testcontainers = "0.27.3"
testcontainers-modules = { version = "0.15", features = ["postgres"] }
reqwest = { workspace = true, features = ["cookies"] }
tower = { version = "0.5", features = ["util"] }

[features]
default = ["openfga"]
keto = ["sso-ory-client/keto"]
openfga = ["sso-openfga-client"]

[build-dependencies]
connectrpc-build = "0.7"
